# Generated by Django 5.2.3 on 2025-07-08 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('half_day', 'half_day')])),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendace', to='employee.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
