# Generated by Django 5.2.3 on 2025-07-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendance'},
        ),
    ]
