# Generated by Django 5.2.3 on 2025-07-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
