# Generated by Django 5.2.3 on 2025-07-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('present', 'present'), ('absent', 'absent'), ('half_day', 'half_day')], null=True),
        ),
    ]
