# Generated by Django 5.2.3 on 2025-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_attendance_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='checkin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent'), ('half_day', 'half_day')], default='absent'),
        ),
    ]
