# Generated by Django 5.2.3 on 2025-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_leave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name_plural': 'Leave'},
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('half_day', 'half_day'), ('full_day', 'full_day')]),
        ),
    ]
