# Generated by Django 5.2.3 on 2025-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('website', models.URLField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
    ]
