# Generated by Django 5.2.3 on 2025-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('intern', 'intern'), ('Backend Developer', 'Backend Developer'), ('HR Manager', 'HR Manager'), ('Frontend Developer', 'Frontend Developer'), ('SEO', 'SEO'), ('Sales Manager', 'Sales Manager')])),
                ('salary', models.CharField(blank=True, null=True)),
                ('entry', models.TimeField()),
                ('exit', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Role',
            },
        ),
    ]
