# Generated by Django 5.2.3 on 2025-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Sick', 'Sick Leave'), ('Casual', 'Casual Leave'), ('Paid', 'Paid Leave')], default='Paid', max_length=20)),
                ('description', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Leave Policy',
            },
        ),
    ]
