# Generated by Django 5.2.4 on 2025-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='leave_count',
            field=models.CharField(blank=True, null=True),
        ),
    ]
