# Generated by Django 5.2.4 on 2025-07-22 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_conversation'),
        ('employee', '0010_alter_leave_options_alter_leave_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField()),
                ('type', models.BooleanField(choices=[('group', 'group'), ('direct', 'direct')])),
                ('uuid', models.CharField(unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_participent', to='employee.employee')),
            ],
            options={
                'verbose_name_plural': 'Room',
            },
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
