# Generated by Django 5.2.4 on 2025-07-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_conversation'),
        ('employee', '0010_alter_leave_options_alter_leave_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_participant', to='employee.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_room', to='communication.room')),
            ],
            options={
                'verbose_name_plural': 'Participent',
            },
        ),
    ]
