# Generated by Django 5.2.4 on 2025-07-25 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_alter_room_participant_alter_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name_plural': 'Participant'},
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='receiver',
        ),
    ]
