# Generated by Django 5.2.4 on 2025-07-25 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_alter_participants_options_and_more'),
        ('employee', '0010_alter_leave_options_alter_leave_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room', to='communication.room'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='employee.employee'),
        ),
    ]
