# Generated by Django 5.2.4 on 2025-07-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_alter_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='remark',
            field=models.CharField(blank=True, null=True),
        ),
    ]
